<?xml version='1.0'?>

<robot name="at1" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:include filename="$(find at1_description)/urdf/at1.gazebo" />
  <xacro:include filename="$(find at1_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find at1_description)/urdf/macros.xacro" />
  <xacro:include filename="$(find at1_description)/urdf/_d435ii.urdf.xacro"/>
  <xacro:include filename="$(find at1_description)/urdf/imu.urdf.xacro" />
  <xacro:include filename="$(find at1_description)/urdf/_materials.urdf.xacro" />
  <xacro:include filename="$(find at1_description)/urdf/_usb_plug.urdf.xacro" />
  <xacro:include filename="$(find at1_description)/urdf/_d435.gazebo.xacro" />

  <xacro:arg name = "camera_topics" default="camera" />
  <xacro:property name="M_PI" value="3.1415926535897931" />

        <xacro:property name="imu_size_x" value="0.004" />
        <xacro:property name="imu_size_y" value="0.006" />
        <xacro:property name="imu_size_z" value="0.001" />
        <xacro:property name="imu_mass" value="0.00001" />
        <xacro:property name="imu_offset_x" value="0.0095" />
        <xacro:property name="imu_offset_y" value="-0.029" />
        <xacro:property name="imu_offset_z" value="0.0021" />

  <!--xacro:property name="d435_cam_depth_to_left_ir_offset" value="0.0"/>
  <xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
  <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>
  <xacro:property name="d435_cam_width" value="0.090"/>
  <xacro:property name="d435_cam_height" value="0.025"/>
  <xacro:property name="d435_cam_depth" value="0.02505"/>
  <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

  <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
  <xacro:property name="d435_cam_depth_py" value="0.0175"/>
  <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/-->


  <link name="robot_footprint"/>

  <link name='chassis'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="10.0"/>
      <origin xyz="0.0 0 0.1" rpy=" 0 0 0"/>
      <inertia
          ixx="0.5" ixy="0" ixz="0"
          iyy="1.0" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='collision'>
      <geometry>
        <box size=".445 .35 .22"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".445 .35 .22"/>
      </geometry>
    </visual>


    <collision name='caster_collision_1'>
      <origin xyz="-0.12 0.135 -0.115" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.04" length="0.035"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>

    <visual name='caster_visual_1'>
      <origin xyz="-0.12 0.135 -0.115" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.04" length="0.035"/>
      </geometry>
    </visual>

    <collision name='caster_collision_2'>
      <origin xyz="-0.12 -0.135 -0.115" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.04" length="0.035"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>

    <visual name='caster_visual_2'>
      <origin xyz="-0.12 -0.135 -0.115" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.04" length="0.035"/>
      </geometry>
    </visual>

  </link>

  <joint name="base_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>
  <link name="left_wheel">
    <origin xyz="0.1 0.13 0.1" rpy="0 1.5707 1.5707"/>
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.04" length="0.035"/>
      </geometry>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.04" length="0.035"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="5"/>
      <cylinder_inertia m="5" r="0.04" h="0.035"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="right_wheel">
    <origin xyz="0.1 -0.13 0.1" rpy="0 1.5707 1.5707"/>
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.04" length="0.035"/>
      </geometry>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="0.04" length="0.035"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="5"/>
      <cylinder_inertia m="5" r="0.04" h="0.035"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>


  <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="0.15 0.135 -0.115" rpy="0 0 0"/>
    <!--origin xyz="0.1 0.13 0" rpy="0 1.5707 1.5707"/-->
    <child link="left_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="0.15 -0.135 -0.115" rpy="0 0 0"/>
    <!--origin xyz="0.1 -0.13 0" rpy="0 1.5707 1.5707"/-->
    <child link="right_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>


  <joint name="rplidar_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz=".16 0 .15" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="rplidar"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="rplidar">
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 1"/>
      <geometry>
        <mesh filename="package://at1_description/meshes/rplidar.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 1"/>
      <geometry>
        <mesh filename="package://at1_description/meshes/rplidar.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>




        <link name="imu_link">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${imu_mass}" />
                <inertia ixx="${imu_mass*(imu_size_y*imu_size_y+imu_size_z*imu_size_z)}" ixy="0" ixz="0"
                         iyy="${imu_mass*(imu_size_x*imu_size_x+imu_size_z*imu_size_z)}" iyz="0"
                         izz="${imu_mass*(imu_size_x*imu_size_x+imu_size_y*imu_size_y)}" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${imu_size_x} ${imu_size_y} ${imu_size_z}" />
                </geometry>
                <material name="red" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${imu_size_x} ${imu_size_y} ${imu_size_z}" />
                </geometry>
            </collision>
        </link>
        <joint name="imu_joint" type="fixed">
            <parent link="chassis" />
            <child link="imu_link" />
            <origin rpy="0 0 0" xyz="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}"/>
        </joint>


  <!-- Realsense -->

  <!--link name="camera_link">
    <visual>
     <origin xyz="0.007 0.065 0.007" rpy="${M_PI/2} 0 ${M_PI/2}"/>
      <geometry>
       <mesh filename="$(find at1_description)/meshes/d435.dae"/-->
       <!--box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.007 0.065 0.007" rpy="1.57 0 1.57"/>
      <geometry>
       <mesh filename="$(find at1_description)/meshes/d435.dae"/-->
       <!--box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/>
      </geometry>
    </collision>
    <inertial>
        < The following are not reliable values, and should not be used for modeling >
      <mass value="0.564" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
    </inertial>
  </link>


  <joint name="3dcamera_joint" type="fixed">
    <origin xyz="0.22 -0.07 0.04" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera_link"/>
  </joint-->


    <sensor_d435i parent="chassis" name = "$(arg camera_topics)" use_nominal_extrinsics = "true" >
     <origin xyz="0.007 0.065 0.012" rpy="${M_PI/2} ${M_PI} 2.9"/>
    </sensor_d435i>




</robot>
